### ISSUE TITLE
SSMW: improvements

### ISSUE THREAD

**Issue by hdghg** [hdghg/overseer#5]
1. ~~Migrations should surely be done in single transaction~~
2. ~~It should try to find another path while it possible~~

**Comment by hdghg** [comment]
[tz.txt](https://github.com/hdghg/overseer/files/40504/tz.txt)

**Comment by olologin** [comment]
Nice, now required set of features became more obvious.

**Comment by hdghg** [comment]
I hope you mean "clear".

**Comment by hdghg** [comment]
Confirmed in production, good job.
